"""
Module that implements all the tools used by the Agents.

Tools:
    - CodeQLSastTool: created a CodeQL database and run SAST analysis 
    - ParseSarifTool: parses the SARIF reports into structured JSON fro LLM
    - WebSearchTool: performs web searches and returns the top 5 results
    - WriteQueryTool: generates CodeQL queries for a given CWE
    - FinishTool: marks the completion of the CreatorAgent
    - FinishToolSuggestor: marks the completion of the SuggestorAgent
    - SuggestTool: generates a detection plan for a new CodeQL query based on a CWE, snippet and existing queries.

Workflow:
    1. Source code is analyzed using CodeQLSastTool
    2. SARIF results are parsed by ParseSarifTool
    3. WebSearchTool can be invoked to gather context or insights
    4. SuggestTool is used by SuggestorAgent to prepare suggestions for new queries
    5. CreatorAgent uses WriteQueryTool and FinishTool to generate queries iteratively.

Args:
    Each tool class takes specific arguments as defined in their respective docstrings.
"""

import os
import json
import subprocess
import shutil

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from config import CODEQL_CLI, CODEQL_DB_PATH, QUERY_PACK, OUTPUT_QUERIES_PATH

def _run_command(command: List[str], step_name: str) -> str:
    """Execute shell command and handles errors.
    
    Args:
        command (List[str]): command to execute
        step_name (str): name of the step for logging
        
    Returns:
        str: standard output of the command

    Raises:
        Exception: if the command fails or CLI not found
    """

    print(f"\n--- {step_name} ---")
    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            check=True,
            shell=False
        )
        print(f"Command executed: {' '.join(command)}")
        return result.stdout
    
    except subprocess.CalledProcessError as e:
        error_msg = f"ERROR in '{step_name}' step. Command failed: {' '.join(command)}. Stderr: {e.stderr}"
        print(error_msg)
        raise Exception(error_msg)
    
    except FileNotFoundError:
        error_msg = f"ERROR: The command '{CODEQL_CLI}' was not found. Ensure that CodeQL CLI is installed and in the PATH."
        print(error_msg)
        raise Exception(error_msg)


def _create_database(source_root: str):
    """
    Creator a CodeQL database from source code.

    Args:
        source_root (str): path to source code directory
    """

    if os.path.exists(CODEQL_DB_PATH):
        print(f"The database '{CODEQL_DB_PATH}' already exists. I delete and recreate it.")
        shutil.rmtree(CODEQL_DB_PATH)

    command = [
        CODEQL_CLI, "database", "create", CODEQL_DB_PATH,
        f"--language=python",
        f"--source-root={source_root}"
    ]
    _run_command(command, "Creation of Database CodeQL")


def _run_analysis(output_report_filepath: str, query_path: Optional[str] = None) -> str:
    """
    Runs CodeQL analysis on a database and generates a SARIF report.
    
    Args:
        output_report_filepath (str): path to dave SARIF report
        query_path (Optional[str]): path to queries or query pack

    Returns:
        str: path to generated SARIF report
    
    """
    
    queries_to_run = query_path if query_path else QUERY_PACK
    
    command = [
        CODEQL_CLI, "database", "analyze", CODEQL_DB_PATH, queries_to_run,
        f"--format=sarifv2.1.0", 
        f"--output={output_report_filepath}"
    ]
    _run_command(command, "Execution of CodeQL Analysis")
    return output_report_filepath


class CodeQLSastTool(BaseModel):
    """
    Tool to execute the SAST analysis (Static Application Security Testing) using CodeQL CLI.
    
    Args:
        source_root (str): directory containig source code
        output_report_filepath (str): SARIF report output path
        query_path (Optional[str]): optional additional queries
    """
    source_root: str = Field(description="Path to the directory containing the source code to be analyzed.")
    output_report_filepath: str = Field(description="Path to the SARIF file where the report generated by CodeQL must be saved.")
    query_path: Optional[str] = Field(default=None, description="Additional .ql or .qls query paths to run. If None, uses the default security query pack.")

    def run(self) -> str:
        """
        Runs the full CodeQL SAST cycle: database creation and analysis.

        Returns:
            str: confirmation massage with SARIF report path
        """

        if not os.path.isdir(self.source_root):
            raise Exception(f"Source root path '{self.source_root}' does not exist.")

        _create_database(self.source_root)
        
        sarif_path = _run_analysis(self.output_report_filepath, self.query_path)
        
        return f"CodeQL SAST analysis completed. SARIF report saved at: {sarif_path}"


class ParseSarifTool(BaseModel):
    """
    Tool to parse SARIF report and produced JSON results for LLM processing.

    Args:
        sarif_filepath (str): path to SARIF JSON file
    """

    sarif_filepath: str = Field(description="Path to the SARIF JSON file generated by CodeQL.")
    
    def run(self) -> str:
        """
        Reads the SARIF file and returns structured JSON.
        
        Returns:
            str: structured JSON string of results.
        """
        if not os.path.exists(self.sarif_filepath):
            raise Exception(f"ERROR: File '{self.sarif_filepath}' does not exist.")
        
        with open(self.sarif_filepath, 'r', encoding='utf-8') as f:
            sarif_data = json.load(f)
        
        structured_res: List[Dict[str, Any]] = []
        
        for runn in sarif_data.get('runs', []):
            tool_name = runn.get('tool', {}).get('driver', {}).get('name', 'CodeQL')

            for result in runn.get('results', []):
                rule_id = result.get('ruleId', 'unknown_rule')
                message = result.get('message', {}).get('text', 'No description')
                
                locations = [
                    {
                        'uri': loc.get('physicalLocation', {}).get('artifactLocation', {}).get('uri', 'unknown_file'),
                        'line': loc.get('physicalLocation', {}).get('region', {}).get('startLine')
                    }
                    for loc in result.get('locations', [])                 
                ]

                structured_res.append({
                    'tool': tool_name,
                    'rule_id': rule_id,
                    'message': message,
                    'locations': locations
                })
        
        return json.dumps(structured_res, indent=2)

from ddgs import DDGS
"""
Exaple usage of DDGS:
results = DDGS().text('live free or die', region='wt-wt', safesearch='off', timelimit='y', max_results=10)

print(results)
[
    {
        "title": "News, sport, celebrities and gossip | The Sun",
        "href": "https://www.thesun.co.uk/",
        "body": "Get the latest news, exclusives, sport, celebrities, showbiz, politics, business and lifestyle from The Sun",
    }, ...
]
"""

class WebSearchTool(BaseModel):
    """
    Tool to perform web searches and return top 5 results.
    
    Args:
        query (str): search query string
    """

    query: str = Field(...)
   
    def run(self, llm=None) -> str:
        """
        Performs the search and returns results as JSON.
        
        Returns:
            str: JSON string of search results or error message
        """
        try:
            results = DDGS().text(self.query, max_results=5)

            list_res = []
            for result in results:
                content = result["body"]
                list_res.append(content)

            return json.dumps(list_res)

        except Exception as e:
            return f"Errore: {str(e)}"



class WriteQueryTool(BaseModel):
    """
    Tool to generate CodeQL query for a given CWE.
    
    Args:
        name_query (str): name of the query file
        cwe (str): CWE identifier
        report (str): structured vulnerability report
    """

    name_query: str = Field(...)
    cwe: str = Field(...)
    report: str = Field(...)

    def run(self, llm) -> str:
        """
        Generates and writes the CodeQL query to disk.
        
        Returns:
            str: success or error message.
        """

        prompt = f"""Role: You are a CodeQL expert specialized in generating production-grade queries.

        You will receive:
        1. A CWE identifier  
        2. A FULL structured vulnerability report produced by another agent  

        Your task is to produce a complete, production-ready CodeQL query based on the rules and detection plan described in the report.

        CWE input: {self.cwe}

        Structured report (mandatory to follow): {self.report}

        RULES: 
        You MUST:
        - Read and use the structured report as the authoritative specification  
        - Generate a real CodeQL query reflecting:
            * The vulnerable pattern  
            * Sources  
            * Sinks  
            * Sanitizers (only if specified in report)  
            * Taint tracking behavior  
            * All relevant AST patterns described  
            * Variant patterns to include  
            * False negatives to avoid  
            * Generalization rules  
        - The query MUST include:
            - CodeQL imports (language + taint modules)
            - Class definitions for identifying sources
            - Class definitions for identifying sinks
            - Class definitions for sanitizers (if report describes them)
            - A full TaintTracking::Configuration implementation
            - The dataflow/ast logic needed to detect ALL patterns in the report
            - A SELECT clause that emits the vulnerability

        You MUST NOT:

        - Output explanations, comments, markdown, or prose
        - Output anything except PURE CodeQL
        - Use placeholders such as TODO or “example”
        - Produce partial code

        Output format:
        - Return ONLY raw CodeQL code.
        - Nothing else.
        - No markdown.
        - No surrounding text.
        - No comments.

        If the output contains anything other than CodeQL, the system will reject it.

        Begin.
        """

        codeql_query = llm.invoke(prompt)

        if hasattr(codeql_query, "content"):
            codeql_query = codeql_query.content

        codeql_query = codeql_query.strip()

        if not os.path.isdir(OUTPUT_QUERIES_PATH):
            return f"ERROR: the {OUTPUT_QUERIES_PATH} directory does not exist."

        filename = self.name_query
        if not filename.endswith('.ql'):
            filename += '.ql'
        filename = filename.replace(" ", "_")

        filepath = os.path.join(OUTPUT_QUERIES_PATH, filename)

        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(codeql_query)
            return f"Success: CodeQL query was written in {filepath}"
        except Exception as e:
            return f"ERROR: {str(e)}"
        

class FinishTool(BaseModel):
    """Tool called by CreatorAgent when work is complete."""
    final_repo: str = Field(...)

        
class FinishToolSuggestor(BaseModel):
    """Tool called by SuggestorAgent when work is complete."""
    final_report: str = Field(...)


class ExistingQuery(BaseModel):
    """Represents an existing CodeQL query for reference."""
    filename: str
    content: str


class SuggestTool(BaseModel):
    """
    Tool to generate a detection plan for a new CodeQL query.
    
    Args:
       cwe (str): target CWE
       description (str): target CWE's description
       snippet (str): code snippet showing the vulnerability
       existing_queries (Optional[List[ExistingQuery]]): list of locally existing queries 
    """

    cwe: str = Field(...)
    description: str = Field(...)
    snippet: str = Field(...)
    existing_queries: Optional[List[ExistingQuery]] = Field(default_factory=list)
    
    def run(self, llm) -> str:
        """
        Generates suggetions a detection plan for a new CodeQL query.

        Returns: 
            str: LLM-generated detection plan.
        """

        existing_queries = "\n\n".join([q.content for q in self.existing_queries])       
        prompt = f"""Role: You are a CodeQL expert.
         
        Instructions: Generate an implementation-ready detection plan for a new CodeQL query targeting:

        CWE: {self.cwe}
        Description: {self.description}
        Snippet of vulnerable code: {self.snippet}

        You can optionally take inspiration from these existing queries: {existing_queries if existing_queries else "None"}

        Your detection plan MUST include:
        1. A precise description of the vulnerable pattern.
        2. Probable sources (isSource candidates).
        3. Probable sinks (isSink candidates).
        4. Potential sanitizers (if applicable).
        5. Relevant AST node patterns (Call, Attribute, BinaryExpr, etc.).
        6. Relevant Python APIs or modules to track.
        7. Required taint-tracking behavior.
        8. Possible variant patterns to detect (predictive generalizations).
        9. False-negative scenarios to avoid.
        10. How this query could generalize to catch unseen patterns.

        Do not output CodeQL code.
        Do not use QL syntax.
        Provide a high-quality conceptual description ready for implementation.
        """

        return llm.invoke(prompt)
     